language: node_js
node_js:
    - "0.12"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0a3029797c884f59b07b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
script:
    - npm run ci
