language: node_js
node_js:
- '4.2'
- '5.7'
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/0a3029797c884f59b07b
    on_success: change
    on_failure: always
    on_start: never
script:
- npm run ci
deploy:
  provider: npm
  email: "zack.t.smith37@gmail.com"
  on:
    tags: true
  api_key:
    secure: p7bRfohf20onEHMcwiM6mHoVjqwKD+apAzuEy0nq/fnI12u9z0vWiA1MCOEAuD9u2W6q5NqtXm0sapWUxfwpmSU2ZYoopfPthKAfOI4+Lo9MCXHziErvKwelKv/Al/5CbCwZQywApfJoaXq5Rl0Xivh/MYCORvETFcAAvSbTFw7nB9LaXKs7Q3eDU6zuUXM4pg8auprGmqJ4NAM7PafuHLg2nkkreCGhv3r7hP4t/p90bBsHu+lCulxZRplsQVKnVUUdKrLTXCtBoo5tw3JJwCkX6daJtAzXybFY71+8+Moi38rmUDwsWMuFNuBpefehppAjAOkyJh74yp/Dc2q33zvfjZCXiSfn9QYoTz0ruaD1y4BETc1V+W5Kl3qoz4eqkXdNeE0YjvMPjq9w+P19+N5pBKT24XLaJ71jHDAUZ3A+Kuz6j+AXSiTJ4CASiUrBCpoDSpbZ6w/THMYHmlrn/jPIk0X8ChCEZ5V90OR3nYK1YiJxbBii9FCBtkC98yqPij1lBpX4YKIgFdy694o+vOec7PvtVcVu0vYgm749LqI97ymNbOFU77m5uKjMoeCHHhuRP0iYyLiyEM08/+Ppz30VGF+B5xzKG9cqfxdAFmY8l939eAnOPbPrTUIGgXuqHXFUtbHjORcLItI53taSve5/fSGlfA3Fpww1ZzTrzwU=
